plugins {
	id 'java'
	id 'eclipse'
	id 'maven-publish'
}

apply from: '../common.gradle'

version = project.mod_version
group = project.dev_group

base {
	archivesName = "${project.archives_base_name}-paper"
}

java {
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

repositories {
	mavenCentral()
	maven {
		name = 'papermc'
		url = 'https://repo.papermc.io/repository/maven-public/'
	}
}

dependencies {
	compileOnly 'io.papermc.paper:paper-api:1.21.4-R0.1-SNAPSHOT'
	compileOnly 'io.netty:netty-codec-http:4.1.100.Final'
}

sourceSets {
	main {
		java {
			srcDir 'src/main/java'
			srcDir '../src/main/java'
			exclude 'wsmc/mixin/**'
			exclude 'wsmc/client/**'
			exclude 'wsmc/api/**'
			exclude 'wsmc/WebSocketConnectionInfo.java'
			exclude 'wsmc/IWebSocketServerAddress.java'
			exclude 'wsmc/IConnectionEx.java'
			exclude 'wsmc/UnitTest.java'
		}
		resources {
			srcDir 'src/main/resources'
		}
	}
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
	options.release = 21
}

tasks.named('jar', Jar).configure {
	manifest {
		attributes([
			'Implementation-Title': project.archives_base_name,
			'Implementation-Version': project.version,
			'Implementation-Vendor': 'Rikka0w0',
			'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
		])
	}
}

processResources {
	duplicatesStrategy = DuplicatesStrategy.INCLUDE
	inputs.property 'version', project.version
	filesMatching('plugin.yml') {
		expand 'version': project.version
	}
}
